basic:
  port: 3000

  redis:
    host: '127.0.0.1'
    port: 6379
    db: 0
    password: '4zbndsfh'

  mysql:
    host: '127.0.0.1'
    port: 3306
    username: 'root'
    password: '4zbndsfh'
    database: 'backend_node'

dev:
  port: 3301
