# 开发环境配置
app:
  https: false
  prefix: '/admin-api'
  host: 'localhost'
  port: 7001
  permission: false
  staticPath: 'public/upload'
# 数据库配置
db:
  mysql:
    host: '127.0.0.1'
    username: 'root'
    password: '4zbndsfh'
    database: 'backend_nest'
    port: 3306
    charset: 'utf8mb4'
    logger: 'advanced-console'
    logging: false
    multipleStatements: true
    dropSchema: false
    synchronize: false
    supportBigNumbers: true
    bigNumberStrings: true

# redis 配置
redis:
  host: '127.0.0.1'
  port: 6379
  db: 0
  password: '4zbndsfh'

# jwt 配置
jwt:
  secretkey: 'YmFja2VuZF9ub2Rl'
  expiresin: '1h'
  # expiresin: '5s'
  refreshExpiresIn: '2h'
# swagger 配置
swagger:
  title: 'Nest-Admin api'
  description: 'Nest-Admin App 接口文档'
  version: '1.0.0'

# 错误码
errorCode:
  valid: 400

# 全局
common:
  # 白名单
  whiteList: []