export default [
  {
    id: '1',
    path: '/system',
    redirect: '/sys/office/index',
    name: '系统管理',
    component: 'LAYOUT',
    meta: {
      icon: 'icon-settings',
      hideMenu: false,
      color: '',
      title: '系统管理',
    },
    children: [
      {
        path: '/sys/tenant/list',
        component: '/sys/tenant/list',
        children: [],
        meta: {
          icon: 'icon-grid',
          hideMenu: false,
          color: '',
          title: '租户管理',
        },
        name: 'ViewsSysTenantList',
        id: '1-1',
        leaf: false,
        url: '/sys/tenant/list',
        target: '',
      },
      {
        path: '/sys/user/index',
        component: '/sys/user/index',
        children: [],
        meta: {
          icon: 'icon-user',
          hideMenu: false,
          color: '',
          title: '用户管理',
        },
        name: 'ViewsSysuserIndex',
        id: '1-2',
        leaf: false,
        url: '/sys/user/index',
        target: '',
      },
      {
        path: '/sys/role/list',
        component: '/sys/role/list',
        meta: {
          icon: 'icon-people',
          hideMenu: false,
          color: '',
          title: '角色管理',
        },
        name: 'ViewsSysRoleList',
        id: '1-3',
        leaf: true,
        url: '/sys/role/list',
        target: '',
      },
      {
        path: '/sys/menu/index',
        component: '/sys/menu/index',
        meta: {
          icon: 'icon-book-open',
          hideMenu: false,
          color: '',
          title: '菜单管理',
        },
        name: 'ViewsSysMenuIndex',
        id: '1-4',
        leaf: true,
        url: '/sys/menu/index',
        target: '',
      },
      {
        path: '/sys/dictType/list',
        component: '/sys/dictType/list',
        children: [
          {
            path: '/sys/dictData/list',
            component: '/sys/dictData/list',
            meta: {
              icon: '',
              hideMenu: true,
              color: '',
              title: '数据查看',
            },
            name: 'ViewsSysDictDataList',
            id: '1-5-1',
            leaf: true,
            url: '/sys/dictData/list',
            target: '',
          },
        ],
        meta: {
          icon: 'icon-social-dropbox',
          hideMenu: false,
          color: '',
          title: '字典管理',
        },
        name: 'ViewsSysDictTypeList',
        id: '1-5',
        leaf: false,
        url: '/sys/dictType/list',
        target: '',
      },
    ],
    leaf: false,
    url: '',
    target: '',
  },
  {
    id: '2',
    path: '/seller',
    redirect: '/seller/order/index',
    name: '商家中心',
    component: 'LAYOUT',
    meta: {
      icon: 'icon-settings',
      hideMenu: false,
      color: '',
      title: '商家中心',
    },
    children: [
      {
        path: '/seller/app',
        redirect: '/seller/app/home/index',
        component: 'LAYOUT',
        children: [
          {
            path: '/seller/app/home/index',
            component: '/seller/app/home/index',
            children: [],
            meta: {
              icon: 'icon-grid',
              hideMenu: false,
              color: '',
              title: '首页图管理',
            },
            name: 'ViewsSysEmpUserIndex',
            id: '2-1-1',
            leaf: false,
            url: '/seller/app/home/index',
            target: '',
          },
        ],
        meta: {
          icon: 'icon-grid',
          hideMenu: false,
          color: '',
          title: '小程序管理',
        },
        name: 'ViewsSellerGoodsIndex',
        id: '2-1',
        leaf: false,
        url: '/seller/goods/index',
        target: '',
      },
      {
        path: '/seller/order/index',
        component: '/seller/order/index',
        children: [],
        meta: {
          icon: 'icon-grid',
          hideMenu: false,
          color: '',
          title: '订单管理',
        },
        name: 'ViewsSellerOrderIndex',
        id: '2-2',
        leaf: false,
        url: '/seller/order/index',
        target: '',
      },
      {
        path: '/seller/user/index',
        component: '/seller/user/index',
        children: [],
        meta: {
          icon: 'icon-grid',
          hideMenu: false,
          color: '',
          title: '用户管理',
        },
        name: 'ViewsSellerUserIndex',
        id: '2-3',
        leaf: false,
        url: '/seller/user/index',
        target: '',
      },
      {
        path: '/seller/goods/index',
        component: '/seller/goods/index',
        children: [],
        meta: {
          icon: 'icon-grid',
          hideMenu: false,
          color: '',
          title: '商品管理',
        },
        name: 'ViewsSellerGoodsIndex',
        id: '2-4',
        leaf: false,
        url: '/seller/goods/index',
        target: '',
      },
      {
        path: '/seller/store/index',
        component: '/seller/store/index',
        children: [],
        meta: {
          icon: 'icon-grid',
          hideMenu: false,
          color: '',
          title: '门店管理',
        },
        name: 'ViewsSellerStoreIndex',
        id: '2-5',
        leaf: false,
        url: '/seller/store/index',
        target: '',
      },
      {
        path: '/seller/memberCard/index',
        component: '/seller/memberCard/index',
        children: [],
        meta: {
          icon: 'icon-grid',
          hideMenu: false,
          color: '',
          title: '会员卡管理',
        },
        name: 'miewsSellerMemberCardIndex',
        id: '2-5',
        leaf: false,
        url: '/seller/memberCard/index',
        target: '',
      },
      {
        path: '/seller/coupon/index',
        component: '/seller/coupon/index',
        children: [],
        meta: {
          icon: 'icon-grid',
          hideMenu: false,
          color: '',
          title: '优惠券管理',
        },
        name: 'miewsSellerCouponIndex',
        id: '2-5',
        leaf: false,
        url: '/seller/coupon/index',
        target: '',
      },
    ],
    leaf: false,
    url: '',
    target: '',
  },
];
